version: "3.8"
services:
  web:
    build: .
    container_name: transaction_analysis_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/transactions_db
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=your_api_key
    depends_on:
      - db
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery_worker
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/transactions_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: celery -A celery_app.celery_app worker --loglevel=info
